### ISSUE TITLE
Grid mesh representation

### ISSUE THREAD

**Issue by dvthuytran** [DavidStotko/Physics-guided-Shape-from-Template#2]
Thank you for a great work !

I would like to try your method on [Phi-SfT](https://4dqv.mpi-inf.mpg.de/phi-SfT) data but it requires remeshing into 32x32 grid. 

Can you please provide me with some details on how to remesh the cloth surfaces ? The remeshed .obj files are highly appreciated.

**Comment by DavidStotko** [comment]
Hi, I'm sorry for the late response.

Unfortunately, I think we are not allowed to distribute the remeshed files publicly due to copyright of the [Phi-SfT](https://4dqv.mpi-inf.mpg.de/phi-SfT) dataset.
Please contact me via E-mail at dstotko@cs.uni-bonn.de to find a solution together.

In short:
We are using Blender tools to get the desired meshes. This is possible by either starting with a plane and match it to the target mesh of Phi-SfT or by remeshing the Phi-SfT mesh to a 32x32 grid. The final mesh should have a grid structure with vertices numbered like this:

![structure](https://github.com/user-attachments/assets/a130df38-dcc2-4a95-870c-aa11522c0313)

**Comment by dvthuytran** [comment]
Thank you for your suggestions.

I tried [harmonic mapping](http://link.springer.com/10.1007/3-540-26808-1_9) to remesh to 32x32 grids. Although they are not as uniform as your data on the paper, I can run the code successfully. There should be some more efforts on remeshing with 3D tools. Small note is the grid should be flipped compared to Phi-SfT template.

I really appreciate your nice work and strong support.
